#1[
#1 TITULO: MAIN
#1 AUTOR: EDUARDO RIBEIRO SILVA DE OLIVEIRA
#1 DATA: 07/10/2024
#1 VERSAO: 1
#1 FINALIDADE: INICIALIZAR O HANDLER DE DATAFRAMES E EXECUTAR SUAS FUNÇÕES
#1 ENTRADAS: NENHUMA
#1 SAIDAS: EXECUÇÃO DAS FUNÇÕES DO DATAFRAMEHANDLER
#1 ROTINAS CHAMADAS: EXECUTE (DATAFRAMEHANDLER)
#1]

from dataframe_logic.dataframe_handler import DataframeHandler

#1[
#1 ROTINA: MAIN
#1 FINALIDADE: CRIA UMA INSTÂNCIA DO DATAFRAMEHANDLER E EXECUTA SUAS FUNÇÕES
#1 ENTRADAS: NENHUMA
#1 DEPENDENCIAS: DATAFRAMEHANDLER
#1 CHAMADO POR: SCRIPT PRINCIPAL
#1 CHAMA: EXECUTE (DATAFRAMEHANDLER)
#1]
#2[
#2 PSEUDOCODIGO DE: MAIN
def main():
    #2 INICIALIZA O HANDLER DE DATAFRAMES
    df_handler = DataframeHandler()
    #2 EXECUTA A FUNÇÃO PRINCIPAL DO HANDLER
    df_handler.execute()
#2]
main()